server:
  port: 8888
  maxHttpHeaderSize: 102400
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: /home/config
  profiles:
    active: native
  application:
    name: config-service
logging:
  level:
    org:
      hibernate:
        type: trace
    ROOT: DEBUG
    org.springframework.web: ERROR
    vn.dnict: DEBUG
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"